### ISSUE TITLE
create desktop version

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/meredith-web-app#29]
https://www.figma.com/file/nIapuABIkKuan4ApGfMLdC/Meredith-navigation-ecommerce?node-id=0%3A1

**Comment by bamboochow** [comment]
Pretty much done? Let me know if you wanna add anything @paulchrisluke 

@atharva3010 link above

**Comment by bamboochow** [comment]
@atharva3010 
Just reconfirming assignment, I wasn't sure if the last assignment includes all edits
If there's anything new, pls update code
